Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import urllib.request
import zipfile
import os

try:
    os.mkdir("files")
except:
    pass

with urllib.request.urlopen('https://courses.cs.tau.ac.il/pyProg/2425a/resources/notebook_resources.zip') as f:
    content = f.read()

with open('files/notebook_resources.zip', 'wb') as f:
    f.write(content)

with zipfile.ZipFile('files/notebook_resources.zip', 'r') as zip_ref:
    zip_ref.extractall('files')

print(os.listdir('files'))
------------------


[31m---------------------------------------------------------------------------[39m
[31mSSLCertVerificationError[39m                  Traceback (most recent call last)
[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/urllib/request.py:1344[39m, in [36mAbstractHTTPHandler.do_open[39m[34m(self, http_class, req, **http_conn_args)[39m
[32m   1343[39m [38;5;28;01mtry[39;00m:
[32m-> [39m[32m1344[39m     [43mh[49m[43m.[49m[43mrequest[49m[43m([49m[43mreq[49m[43m.[49m[43mget_method[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mreq[49m[43m.[49m[43mselector[49m[43m,[49m[43m [49m[43mreq[49m[43m.[49m[43mdata[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m
[32m   1345[39m [43m              [49m[43mencode_chunked[49m[43m=[49m[43mreq[49m[43m.[49m[43mhas_header[49m[43m([49m[33;43m'[39;49m[33;43mTransfer-encoding[39;49m[33;43m'[39;49m[43m)[49m[43m)[49m
[32m   1346[39m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/http/client.py:1327[39m, in [36mHTTPConnection.request[39m[34m(self, method, url, body, headers, encode_chunked)[39m
[32m   1326[39m [38;5;250m[39m[33;03m"""Send a complete request to the server."""[39;00m
[32m-> [39m[32m1327[39m [38;5;28;43mself[39;49m[43m.[49m[43m_send_request[49m[43m([49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mbody[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m)[49m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/http/client.py:1373[39m, in [36mHTTPConnection._send_request[39m[34m(self, method, url, body, headers, encode_chunked)[39m
[32m   1372[39m     body = _encode(body, [33m'[39m[33mbody[39m[33m'[39m)
[32m-> [39m[32m1373[39m [38;5;28;43mself[39;49m[43m.[49m[43mendheaders[49m[43m([49m[43mbody[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m=[49m[43mencode_chunked[49m[43m)[49m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/http/client.py:1322[39m, in [36mHTTPConnection.endheaders[39m[34m(self, message_body, encode_chunked)[39m
[32m   1321[39m     [38;5;28;01mraise[39;00m CannotSendHeader()
[32m-> [39m[32m1322[39m [38;5;28;43mself[39;49m[43m.[49m[43m_send_output[49m[43m([49m[43mmessage_body[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m=[49m[43mencode_chunked[49m[43m)[49m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/http/client.py:1081[39m, in [36mHTTPConnection._send_output[39m[34m(self, message_body, encode_chunked)[39m
[32m   1080[39m [38;5;28;01mdel[39;00m [38;5;28mself[39m._buffer[:]
[32m-> [39m[32m1081[39m [38;5;28;43mself[39;49m[43m.[49m[43msend[49m[43m([49m[43mmsg[49m[43m)[49m
[32m   1083[39m [38;5;28;01mif[39;00m message_body [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m   1084[39m 
[32m   1085[39m     [38;5;66;03m# create a consistent interface to message_body[39;00m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/http/client.py:1025[39m, in [36mHTTPConnection.send[39m[34m(self, data)[39m
[32m   1024[39m [38;5;28;01mif[39;00m [38;5;28mself[39m.auto_open:
[32m-> [39m[32m1025[39m     [38;5;28;43mself[39;49m[43m.[49m[43mconnect[49m[43m([49m[43m)[49m
[32m   1026[39m [38;5;28;01melse[39;00m:

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/http/client.py:1468[39m, in [36mHTTPSConnection.connect[39m[34m(self)[39m
[32m   1466[39m     server_hostname = [38;5;28mself[39m.host
[32m-> [39m[32m1468[39m [38;5;28mself[39m.sock = [38;5;28;43mself[39;49m[43m.[49m[43m_context[49m[43m.[49m[43mwrap_socket[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43msock[49m[43m,[49m
[32m   1469[39m [43m                                      [49m[43mserver_hostname[49m[43m=[49m[43mserver_hostname[49m[43m)[49m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/ssl.py:455[39m, in [36mSSLContext.wrap_socket[39m[34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)[39m
[32m    449[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mwrap_socket[39m([38;5;28mself[39m, sock, server_side=[38;5;28;01mFalse[39;00m,
[32m    450[39m                 do_handshake_on_connect=[38;5;28;01mTrue[39;00m,
[32m    451[39m                 suppress_ragged_eofs=[38;5;28;01mTrue[39;00m,
[32m    452[39m                 server_hostname=[38;5;28;01mNone[39;00m, session=[38;5;28;01mNone[39;00m):
[32m    453[39m     [38;5;66;03m# SSLSocket class handles server_hostname encoding before it calls[39;00m
[32m    454[39m     [38;5;66;03m# ctx._wrap_socket()[39;00m
[32m--> [39m[32m455[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43msslsocket_class[49m[43m.[49m[43m_create[49m[43m([49m
[32m    456[39m [43m        [49m[43msock[49m[43m=[49m[43msock[49m[43m,[49m
[32m    457[39m [43m        [49m[43mserver_side[49m[43m=[49m[43mserver_side[49m[43m,[49m
[32m    458[39m [43m        [49m[43mdo_handshake_on_connect[49m[43m=[49m[43mdo_handshake_on_connect[49m[43m,[49m
[32m    459[39m [43m        [49m[43msuppress_ragged_eofs[49m[43m=[49m[43msuppress_ragged_eofs[49m[43m,[49m
[32m    460[39m [43m        [49m[43mserver_hostname[49m[43m=[49m[43mserver_hostname[49m[43m,[49m
[32m    461[39m [43m        [49m[43mcontext[49m[43m=[49m[38;5;28;43mself[39;49m[43m,[49m
[32m    462[39m [43m        [49m[43msession[49m[43m=[49m[43msession[49m
[32m    463[39m [43m    [49m[43m)[49m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/ssl.py:1046[39m, in [36mSSLSocket._create[39m[34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)[39m
[32m   1045[39m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33m"[39m[33mdo_handshake_on_connect should not be specified for non-blocking sockets[39m[33m"[39m)
[32m-> [39m[32m1046[39m         [38;5;28;43mself[39;49m[43m.[49m[43mdo_handshake[49m[43m([49m[43m)[49m
[32m   1047[39m [38;5;28;01mexcept[39;00m ([38;5;167;01mOSError[39;00m, [38;5;167;01mValueError[39;00m):

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/ssl.py:1321[39m, in [36mSSLSocket.do_handshake[39m[34m(self, block)[39m
[32m   1320[39m         [38;5;28mself[39m.settimeout([38;5;28;01mNone[39;00m)
[32m-> [39m[32m1321[39m     [38;5;28;43mself[39;49m[43m.[49m[43m_sslobj[49m[43m.[49m[43mdo_handshake[49m[43m([49m[43m)[49m
[32m   1322[39m [38;5;28;01mfinally[39;00m:

[31mSSLCertVerificationError[39m: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

[31mURLError[39m                                  Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 10[39m
[32m      7[39m [38;5;28;01mexcept[39;00m:
[32m      8[39m     [38;5;28;01mpass[39;00m
[32m---> [39m[32m10[39m [38;5;28;01mwith[39;00m [43murllib[49m[43m.[49m[43mrequest[49m[43m.[49m[43murlopen[49m[43m([49m[33;43m'[39;49m[33;43mhttps://courses.cs.tau.ac.il/pyProg/2425a/resources/notebook_resources.zip[39;49m[33;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[32m     11[39m     content = f.read()
[32m     13[39m [38;5;28;01mwith[39;00m [38;5;28mopen[39m([33m'[39m[33mfiles/notebook_resources.zip[39m[33m'[39m, [33m'[39m[33mwb[39m[33m'[39m) [38;5;28;01mas[39;00m f:

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/urllib/request.py:215[39m, in [36murlopen[39m[34m(url, data, timeout, cafile, capath, cadefault, context)[39m
[32m    213[39m [38;5;28;01melse[39;00m:
[32m    214[39m     opener = _opener
[32m--> [39m[32m215[39m [38;5;28;01mreturn[39;00m [43mopener[49m[43m.[49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/urllib/request.py:515[39m, in [36mOpenerDirector.open[39m[34m(self, fullurl, data, timeout)[39m
[32m    512[39m     req = meth(req)
[32m    514[39m sys.audit([33m'[39m[33murllib.Request[39m[33m'[39m, req.full_url, req.data, req.headers, req.get_method())
[32m--> [39m[32m515[39m response = [38;5;28;43mself[39;49m[43m.[49m[43m_open[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m
[32m    517[39m [38;5;66;03m# post-process response[39;00m
[32m    518[39m meth_name = protocol+[33m"[39m[33m_response[39m[33m"[39m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/urllib/request.py:532[39m, in [36mOpenerDirector._open[39m[34m(self, req, data)[39m
[32m    529[39m     [38;5;28;01mreturn[39;00m result
[32m    531[39m protocol = req.type
[32m--> [39m[32m532[39m result = [38;5;28;43mself[39;49m[43m.[49m[43m_call_chain[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43mhandle_open[49m[43m,[49m[43m [49m[43mprotocol[49m[43m,[49m[43m [49m[43mprotocol[49m[43m [49m[43m+[49m
[32m    533[39m [43m                          [49m[33;43m'[39;49m[33;43m_open[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43mreq[49m[43m)[49m
[32m    534[39m [38;5;28;01mif[39;00m result:
[32m    535[39m     [38;5;28;01mreturn[39;00m result

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/urllib/request.py:492[39m, in [36mOpenerDirector._call_chain[39m[34m(self, chain, kind, meth_name, *args)[39m
[32m    490[39m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[32m    491[39m     func = [38;5;28mgetattr[39m(handler, meth_name)
[32m--> [39m[32m492[39m     result = [43mfunc[49m[43m([49m[43m*[49m[43margs[49m[43m)[49m
[32m    493[39m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m    494[39m         [38;5;28;01mreturn[39;00m result

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/urllib/request.py:1392[39m, in [36mHTTPSHandler.https_open[39m[34m(self, req)[39m
[32m   1391[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mhttps_open[39m([38;5;28mself[39m, req):
[32m-> [39m[32m1392[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43mdo_open[49m[43m([49m[43mhttp[49m[43m.[49m[43mclient[49m[43m.[49m[43mHTTPSConnection[49m[43m,[49m[43m [49m[43mreq[49m[43m,[49m
[32m   1393[39m [43m                        [49m[43mcontext[49m[43m=[49m[38;5;28;43mself[39;49m[43m.[49m[43m_context[49m[43m)[49m

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/urllib/request.py:1347[39m, in [36mAbstractHTTPHandler.do_open[39m[34m(self, http_class, req, **http_conn_args)[39m
[32m   1344[39m         h.request(req.get_method(), req.selector, req.data, headers,
[32m   1345[39m                   encode_chunked=req.has_header([33m'[39m[33mTransfer-encoding[39m[33m'[39m))
[32m   1346[39m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m
[32m-> [39m[32m1347[39m         [38;5;28;01mraise[39;00m URLError(err)
[32m   1348[39m     r = h.getresponse()
[32m   1349[39m [38;5;28;01mexcept[39;00m:

[31mURLError[39m: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

